language: node_js
node_js:
   - "0.10"
notifications:
  recipients:
    - github@ernie.org
  email:
    on_success: always
    on_failure: always

# before_install: sudo apt-get install libtext-csv-perl
